<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250503185646 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema for Linkuy Connect, including seed data';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
                CREATE TABLE public.family (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    name VARCHAR(255) NOT NULL,
                    active BOOLEAN DEFAULT true NOT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    PRIMARY KEY(id)
                )
            SQL
        );

        $this->addSql(<<<'SQL'
                CREATE TABLE public."user" (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    email VARCHAR(255) NOT NULL,
                    password VARCHAR(255) NOT NULL,
                    user_type VARCHAR(255) NOT NULL,
                    active BOOLEAN DEFAULT false NOT NULL,
                    device_token VARCHAR(255) DEFAULT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    family_id INT NOT NULL,
                    PRIMARY KEY(id)
                )
            SQL
        );
        $this->addSql('CREATE UNIQUE INDEX UNIQ_327C5DE7E7927C74 ON public."user" (email)');
        $this->addSql('CREATE INDEX IDX_327C5DE7C35E566A ON public."user" (family_id)');

        $this->addSql(<<<'SQL'
                CREATE TABLE public.settings (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    inactivity_threshold SMALLINT DEFAULT 30 NOT NULL,
                    do_not_disturb_start_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
                    do_not_disturb_end_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
                    do_not_disturb BOOLEAN DEFAULT false NOT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    family_id INT NOT NULL,
                    PRIMARY KEY(id)
                )
            SQL
        );
        $this->addSql('CREATE INDEX IDX_27A97BACC35E566A ON public.settings (family_id)');

        $this->addSql(<<<'SQL'
                CREATE TABLE public.notification (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    message TEXT NOT NULL,
                    sent BOOLEAN DEFAULT false NOT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    user_id INT NOT NULL,
                    family_id INT NOT NULL,
                    PRIMARY KEY(id)
                )
            SQL
        );
        $this->addSql('CREATE INDEX IDX_FF070BEEA76ED395 ON public.notification (user_id)');
        $this->addSql('CREATE INDEX IDX_FF070BEEC35E566A ON public.notification (family_id)');

        $this->addSql(<<<'SQL'
                CREATE TABLE public.activity_log (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    type VARCHAR(255) NOT NULL,
                    steps INT DEFAULT NULL,
                    distance_km DOUBLE PRECISION DEFAULT NULL,
                    latitude DOUBLE PRECISION DEFAULT NULL,
                    longitude DOUBLE PRECISION DEFAULT NULL,
                    accuracy_meters DOUBLE PRECISION DEFAULT NULL,
                    metadata JSON DEFAULT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                    user_id INT NOT NULL,
                    PRIMARY KEY(id)
                )
            SQL
        );
        $this->addSql('CREATE INDEX idx_activity_user ON public.activity_log (user_id)');
        $this->addSql('CREATE INDEX idx_activity_type ON public.activity_log (type)');
        $this->addSql('CREATE INDEX idx_activity_user_created_at ON public.activity_log (user_id, created_at)');

        $this->addSql('ALTER TABLE public."user" ADD CONSTRAINT FK_327C5DE7C35E566A FOREIGN KEY (family_id) REFERENCES public.family (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE public.settings ADD CONSTRAINT FK_27A97BACC35E566A FOREIGN KEY (family_id) REFERENCES public.family (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE public.notification ADD CONSTRAINT FK_FF070BEEA76ED395 FOREIGN KEY (user_id) REFERENCES public."user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE public.notification ADD CONSTRAINT FK_FF070BEEC35E566A FOREIGN KEY (family_id) REFERENCES public.family (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE public.activity_log ADD CONSTRAINT FK_BD558B63A76ED395 FOREIGN KEY (user_id) REFERENCES public."user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql("
            INSERT INTO family (id, name, created_at, updated_at)
            VALUES (1, 'Familia UNIR', NOW(), NOW())
        ");

        $this->addSql("
            INSERT INTO \"user\" (id, email, password, user_type, active, family_id, device_token, created_at, updated_at)
            VALUES (
                1,
                'cuidador@unir.com',
                '\$2y\$13\$HLxNudVBsBnTYOxVa28G8OMbTjFowPzYXCMD9NTl62PcahyRcRSSK',
                'ROLE_CAREGIVER',
                true,
                1,
                'ExponentPushToken[N_gj6CE-v5H4cHOxsmWmKa]',
                NOW(),
                NOW()
            )
        ");

        $this->addSql("
            INSERT INTO \"user\" (id, email, password, user_type, active, family_id, device_token, created_at, updated_at)
            VALUES (
                2,
                'adulto@unir.com',
                '\$2y\$13\$A7iKlYodqWiDt9bhPOXN/OlFQO8TQzj4oUsaIbp2ViAdIxJsHxn3C',
                'ROLE_SENIOR',
                true,
                1,
                NULL,
                NOW(),
                NOW()
            )
        ");

        $this->addSql("
            INSERT INTO settings (id, inactivity_threshold, do_not_disturb_start_time, do_not_disturb, created_at, updated_at, family_id, do_not_disturb_end_time)
            VALUES (
                1,
                30,
                '23:00:00',
                true,
                NOW(),
                NOW(),
                1,
                '06:10:00'
            )
        ");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE public.activity_log DROP CONSTRAINT FK_BD558B63A76ED395');
        $this->addSql('ALTER TABLE public.notification DROP CONSTRAINT FK_FF070BEEA76ED395');
        $this->addSql('ALTER TABLE public.notification DROP CONSTRAINT FK_FF070BEEC35E566A');
        $this->addSql('ALTER TABLE public.settings DROP CONSTRAINT FK_27A97BACC35E566A');
        $this->addSql('ALTER TABLE public."user" DROP CONSTRAINT FK_327C5DE7C35E566A');
        $this->addSql('DROP TABLE public.activity_log');
        $this->addSql('DROP TABLE public.notification');
        $this->addSql('DROP TABLE public.settings');
        $this->addSql('DROP TABLE public."user"');
        $this->addSql('DROP TABLE public.family');
    }
}
