controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
    path: /api/login
    controller: Lexik\Bundle\JWTAuthenticationBundle\Controller\AuthenticationController::login

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
